// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu2DyGeEOVkIo4eq19SGhL3LcJguxMkag',
    appId: '1:216085873193:web:2ca4ea6b7a947201049238',
    messagingSenderId: '216085873193',
    projectId: 'movil-4b5c5',
    authDomain: 'movil-4b5c5.firebaseapp.com',
    storageBucket: 'movil-4b5c5.appspot.com',
    measurementId: 'G-B01YP3JCXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xd_pgPmzHXXETU7BGT8IgmfsrtsvtYc',
    appId: '1:216085873193:android:b4e164c2025363eb049238',
    messagingSenderId: '216085873193',
    projectId: 'movil-4b5c5',
    storageBucket: 'movil-4b5c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_89x4XvrICgjihIW_39FpyZfpkQCxkHg',
    appId: '1:216085873193:ios:38189ab6fc4c23eb049238',
    messagingSenderId: '216085873193',
    projectId: 'movil-4b5c5',
    storageBucket: 'movil-4b5c5.appspot.com',
    iosBundleId: 'com.example.menu2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_89x4XvrICgjihIW_39FpyZfpkQCxkHg',
    appId: '1:216085873193:ios:38189ab6fc4c23eb049238',
    messagingSenderId: '216085873193',
    projectId: 'movil-4b5c5',
    storageBucket: 'movil-4b5c5.appspot.com',
    iosBundleId: 'com.example.menu2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu2DyGeEOVkIo4eq19SGhL3LcJguxMkag',
    appId: '1:216085873193:web:2fb0e1a7f971beb4049238',
    messagingSenderId: '216085873193',
    projectId: 'movil-4b5c5',
    authDomain: 'movil-4b5c5.firebaseapp.com',
    storageBucket: 'movil-4b5c5.appspot.com',
    measurementId: 'G-P3Q2G0BXX6',
  );
}
